name: CI
on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install
      - run: npx playwright install --with-deps chromium
      - run: npx playwright test --grep-invert "Dashboard shows zero results"
        env:
          TESTRELIC_API_KEY: ${{ secrets.TESTRELIC_API_KEY }}